build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Rehau Neasmart2.0 Gateway Homeassistant Add-On"
  org.opencontainers.image.description: "Addon to gap the bridge between Rehau Neasmart2.0 Sysbus and homeassistant"
  org.opencontainers.image.source: "https://github.com/MatteoManzoni/RehauNeasmart2.0_Gateway"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  GO_VERSION: "1.20.5"
