name: Rehau Neasmart 2.0 Gateway
version: "0.1.12"
slug: rehau_neasmart_gateway
description: Shim between Rehau Neasmart 2.0 Modbus RTU-Serial/TCP and REST
url: "https://github.com/matteomanzoni/rehauneasmart2.0_gateway/blob/main/rehau_neasmart2.0_gateway"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
init: false
uart: true
apparmor: false
startup: services
image: "ghcr.io/matteomanzoni/{arch}-rehau_neasmart2_gateway"
ports:
  502/tcp: 502
  5000/tcp: 5000
options:
  listen_address: "0.0.0.0"
  listen_port: "502"
  server_type: "tcp"
  slave_id: 240
schema:
  listen_address: "str?"
  listen_port: "str?"
  server_type: "str?"
  slave_id: "int?"
